version: '3.7'

# Backend API
services:
  smart-brain-api:
    container_name: backend
    # image: node:12.16.2
    build: ./
    command: npm start
    working_dir: /usr/src/smart-brain-api
    environment:
      POSTGRES_URI: postgres://haipa:secret@postgres/smart-brain-docker
      REDIS_URI: redis://redis:6379
    links:
      - postgres
      - redis
    ports:
      - '3000:3000'
    volumes:
      - //c/Users/cmyaz/Documents/Programming_Projects/SmartBrainAPI:/usr/src/smart-brain-api
  # Postgres
  postgres:
    environment:
      POSTGRES_USER: haipa
      POSTGRES_PASSWORD: secret
      POSTGRES_DB: smart-brain-docker
      POSTGRES_HOST: postgres
    build: ./postgres
    ports:
      - '5432:5432'

  # Redis
  redis:
    image: redis
    ports:
      - '6379:6379'
